// INCLUDE FILE generated by "Pelles C for Windows, version 1.00".

#define DLG_MAIN  1001
#define IDR_ICO_MAIN  8001
#define ID_PRINT  1
#define IDC_PRINT  4001

#define IDC_CODE  4005



#define IDC_SETPRINTER  4013
#define IDC_VERSION  4014
#define IDC_TEST  4015
#define IDC_STOCK  4003

#define IDC_STARTDATE  4009
#define IDC_ENDDATE  4011
#define IDC_COUNT  4012
#define IDC_MSG  4016
#define IDC_PRINTER  4017
#define IDC_TEST1  4019
#define IDC_CYCLE  4004
#define IDC_CONTEXT  4007
#define IDC_TO  4010
